# Generated by Django 4.1.7 on 2023-03-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
    ]
