# Generated by Django 4.1.7 on 2023-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
